#pragma once

void initializeData();
void displayMenu();
void listStudents();
void listCourses();
void listTeachers();
void listRecords();
void queryStudent();
void queryCourse();
void queryTeacher();
void queryRecord();
void addStudent();
void addCourse();
void addTeacher();
void addRecord();
void deleteStudent();
void deleteCourse();
void deleteTeacher();
void deleteRecord();
void updateStudent();
void updateCourse();
void updateTeacher();
